version: '3.8'
services:
    dvwa:
      image: vulnerables/web-dvwa
      container_name: vulnerable-dvwa
      ports:
        - "80:80"
      volumes:
        - ./config/config.inc.php:/var/www/html/config/config.inc.php
      networks:
        - dvwa_stack
      restart: always

    mariadb:
      image: mariadb:10.7
      container_name: vulnerable-dvwa-mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=dvwa
        - MYSQL_USER=dvwa
        - MYSQL_PASSWORD=dvwa
      ports:
        - "3306:3306"
      networks:
        - dvwa_stack
      restart: always

    adminer:
      container_name: vulnerable-dvwa-adminer
      image: adminer
      ports:
        - "8080:8080"
      networks:
          - dvwa_stack
networks:
  dvwa_stack:
    driver: bridge